export enum ActionType {
    // Application state
    SET_ERROR = 'SET_ERROR',
    DISMISS_ERROR = 'DISMISS_ERROR',
    SET_LOADING = 'SET_LOADING',
    SET_TITLE = 'SET_TITLE',

    // Authentication state
    AUTHENTICATED = 'AUTHENTICATED',
    DEAUTHENTICATED = 'DEAUTHENTICATED',

    // Authentication actions
    AUTHENTICATE = 'AUTHENTICATE',
    DEAUTHENTICATE = 'DEAUTHENTICATE',
    SIGNUP = 'SIGNUP',

    // Project state
    SET_PROJECTS = 'SET_PROJECTS',
    SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT',

    // Project actions
    FETCH_PROJECTS = 'FETCH_PROJECTS',
    FETCH_CURRENT_PROJECT = 'FETCH_CURRENT_PROJECT',
    CREATE_PROJECT = 'CREATE_PROJECT',
    UPDATE_PROJECT = 'UPDATE_PROJECT',
    CREATE_TODO_LIST = 'CREATE_TODO_LIST',
    CREATE_TODO_ITEM = 'CREATE_TODO_ITEM',
    UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM',
    DELETE_TODO_ITEM = 'DELETE_TODO_ITEM',

    // Settings
    TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME',
    SET_TOKEN = 'SET_TOKEN',
};