export enum ActionType {
    // Application state
    SET_ERROR = 'SET_ERROR',
    DISMISS_ERROR = 'DISMISS_ERROR',
    SET_LOADING = 'SET_LOADING',
    SET_TITLE = 'SET_TITLE',

    // Authentication state
    AUTHENTICATED = 'AUTHENTICATED',
    DEAUTHENTICATED = 'DEAUTHENTICATED',

    // Authentication actions
    AUTHENTICATE = 'AUTHENTICATE',
    DEAUTHENTICATE = 'DEAUTHENTICATE',
    SIGNUP = 'SIGNUP',

    // Project state
    SET_PROJECTS = 'SET_PROJECTS',
    SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT',

    // Project actions
    FETCH_PROJECTS = 'FETCH_PROJECTS',
    FETCH_CURRENT_PROJECT = 'FETCH_CURRENT_PROJECT',

    // Settings
    TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME',
    SET_TOKEN = 'SET_TOKEN',
};